logging:
  level:
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: info
    org.apache.catalina.core.StandardService: info
    #com.xflib.framework.configuration.redis: debug
    #com.xflib.framework.redis: debug
    root: error

spring:
  application:
    name: test-dynamic-database-service
  datasource:
      url: jdbc:mysql://192.168.1.252/kxlist_user?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

custom:
  datasource:
    sites: default, 30001,30002,30003
    list:
      -
        site: 30001
        sources:
          -
            source: master
            config:
              url: jdbc:mysql://127.0.0.1:3306/dbdefault?characterEncoding=utf-8&useSSL=false
              username: root
              password: fkR/CCI7T2Um
              driver-class-name: com.mysql.jdbc.Driver
          -
            source: slave
            config:
              url: jdbc:mysql://127.0.0.1:3306/db30001?characterEncoding=utf-8&useSSL=false
              username: root
              password: fkR/CCI7T2Um
              driver-class-name: com.mysql.jdbc.Driver
      -
        site: 30002
        sources:
          -
            source: master
            config:
              url: jdbc:mysql://127.0.0.1:3306/db30002?characterEncoding=utf-8&useSSL=false
              username: root
              password: fkR/CCI7T2Um
              driver-class-name: com.mysql.jdbc.Driver

# 测试类，禁止可靠删除或设置为false
demo.enabled:
  sampleCommandLineRunner: true
  sampleCommandLineRunner2: true
